// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The event sidebar is generated from the docs folder structure, ordered by
 * each page's sidebar_position front matter.
 *
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  eventSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
